import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

async function getAIConfig() {
  try {
    const settings = await prisma.systemSetting.findMany({
      where: { key: { in: ['GEMINI_API_KEY', 'AI_MODEL'] } }
    });
    const keySetting = settings.find(s => s.key === 'GEMINI_API_KEY');
    const modelSetting = settings.find(s => s.key === 'AI_MODEL');
    return {
      apiKey: keySetting?.value || process.env.GEMINI_API_KEY || null,
      model: modelSetting?.value || 'gemini-1.5-flash',
    };
  } catch {
    return { apiKey: process.env.GEMINI_API_KEY || null, model: 'gemini-1.5-flash' };
  }
}

export async function GET(request: Request, { params }: { params: { id: string } }) {
  try {
    const { id } = params;

    const incident = await prisma.incident.findFirst({
      where: { OR: [{ id }, { number: id }] },
      include: {
        updates: { orderBy: { updateNumber: 'asc' } },
        sites: { include: { site: true } },
      },
    });

    if (!incident) {
      return NextResponse.json({ success: false, error: 'Incident not found' }, { status: 404 });
    }

    // Build the resolution summary from incident fields
    const resolutionSummary = {
      resolvedAt: incident.resolvedAt?.toISOString() || null,
      closedAt: incident.closedAt?.toISOString() || null,
      totalOutageDuration: incident.totalOutageDuration || null,
      rootCause: incident.aiRootCause || null,
      businessImpact: incident.aiBusinessImpact || null,
      technicalSummary: incident.aiTechnicalSummary || null,
      assignmentGroup: incident.assignmentGroup,
      assignedTo: incident.assignedTo || null,
      priority: incident.priority,
      status: incident.status,
      impactedSites: incident.sites?.map((s: any) => s.site?.name).filter(Boolean) || [],
    };

    // Build auto-generated RCA from incident notes/updates
    const updateNotes = incident.updates?.map((u) => ({
      updateNumber: u.updateNumber,
      comment: u.comment,
      author: u.authorName,
      timestamp: u.createdAt.toISOString(),
      isFinal: u.isFinal,
    })) || [];

    // Try AI-powered RCA generation
    let autoGeneratedRca: any = null;
    const { apiKey, model } = await getAIConfig();

    if (apiKey && updateNotes.length > 0) {
      try {
        const prompt = `You are an expert IT incident analyst. Based on the following incident details and timeline updates, generate a structured Root Cause Analysis (RCA).

INCIDENT DETAILS:
- Number: ${incident.number}
- Short Description: ${incident.shortDescription}
- Description: ${incident.description || 'N/A'}
- Priority: ${incident.priority}
- CTI: ${incident.cti || 'N/A'}
- Assignment Group: ${incident.assignmentGroup}
- Impacted Sites: ${resolutionSummary.impactedSites.join(', ') || 'N/A'}
- Total Outage Duration: ${incident.totalOutageDuration || 'N/A'}
- Opened At: ${incident.openedAt?.toISOString() || 'N/A'}
- Resolved At: ${incident.resolvedAt?.toISOString() || 'N/A'}

TIMELINE UPDATES (chronological):
${updateNotes.map(u => `[Update #${u.updateNumber}] (${u.timestamp}) by ${u.author}: ${u.comment}`).join('\n')}

AI GENERATED FIELDS (if available):
- Root Cause: ${incident.aiRootCause || 'Not determined'}
- Business Impact: ${incident.aiBusinessImpact || 'Not determined'}
- Technical Summary: ${incident.aiTechnicalSummary || 'Not determined'}
- What Was Done: ${incident.aiDoneSoFar || 'Not determined'}

Generate a JSON response with this EXACT structure (no markdown, no code blocks, only valid JSON):
{
  "summary": "A 2-3 sentence high-level summary of the incident and its resolution",
  "rootCause": "The determined root cause of the incident",
  "timeline": ["Key milestone 1 with timestamp", "Key milestone 2 with timestamp"],
  "impactAnalysis": "Description of the business and technical impact",
  "resolutionSteps": ["Step 1 taken to resolve", "Step 2 taken to resolve"],
  "preventiveMeasures": ["Recommendation 1 to prevent recurrence", "Recommendation 2"],
  "lessonsLearned": ["Lesson 1", "Lesson 2"],
  "fiveWhyAnalysis": [
    {"why": "Why did the incident occur?", "answer": "Because..."},
    {"why": "Why did [answer 1] happen?", "answer": "Because..."},
    {"why": "Why did [answer 2] happen?", "answer": "Because..."},
    {"why": "Why did [answer 3] happen?", "answer": "Because..."},
    {"why": "Why did [answer 4] happen?", "answer": "The root cause is..."}
  ]
}`;

        const res = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{ parts: [{ text: prompt }] }],
              generationConfig: { temperature: 0.3, responseMimeType: 'application/json' },
            }),
          }
        );

        if (res.ok) {
          const data = await res.json();
          const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
          if (text) {
            autoGeneratedRca = JSON.parse(text);
          }
        }

        if (!autoGeneratedRca) {
          autoGeneratedRca = buildFallbackRca(incident, updateNotes);
        }
      } catch (aiError: any) {
        console.error('[RCA API] AI generation failed:', aiError.message);
        autoGeneratedRca = buildFallbackRca(incident, updateNotes);
      }
    } else {
      // No AI key or no updates - build from available data
      autoGeneratedRca = buildFallbackRca(incident, updateNotes);
    }

    return NextResponse.json({
      success: true,
      rca: {
        autoGeneratedRca,
        resolutionSummary,
        updateNotes,
      },
    });
  } catch (err: any) {
    console.error('[RCA API] Error:', err.message);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}

function buildFallbackRca(incident: any, updateNotes: any[]) {
  const finalUpdate = updateNotes.find(u => u.isFinal);
  const lastUpdate = updateNotes[updateNotes.length - 1];

  return {
    summary: `Incident ${incident.number} ("${incident.shortDescription}") was raised as ${incident.priority} priority and handled by ${incident.assignmentGroup}. ${incident.totalOutageDuration ? `Total outage duration was ${incident.totalOutageDuration}.` : 'The incident has been resolved.'}`,
    rootCause: incident.aiRootCause || 'Root cause analysis pending — insufficient data for automated determination.',
    timeline: updateNotes.map(u => `[Update #${u.updateNumber}] ${new Date(u.timestamp).toLocaleString()}: ${u.comment.substring(0, 120)}${u.comment.length > 120 ? '...' : ''}`),
    impactAnalysis: incident.aiBusinessImpact || `The incident impacted operations${incident.sites?.length ? ` across ${incident.sites.length} site(s)` : ''}. ${incident.priority === 'P1' ? 'This was classified as a critical priority incident requiring immediate attention.' : 'This was classified as a high priority incident.'}`,
    resolutionSteps: finalUpdate
      ? [finalUpdate.comment]
      : lastUpdate
        ? [lastUpdate.comment]
        : ['Resolution details not yet documented in timeline updates.'],
    preventiveMeasures: ['Conduct post-incident review with all stakeholders', 'Review and update relevant SOPs and runbooks', 'Implement additional monitoring for early detection'],
    lessonsLearned: ['Document detailed resolution steps for future reference', 'Review escalation procedures and response times'],
    fiveWhyAnalysis: [
      {
        why: `Why did incident ${incident.number} occur?`,
        answer: incident.shortDescription || 'An unexpected service degradation or outage was reported.',
      },
      {
        why: 'Why was the service degraded or unavailable?',
        answer: incident.aiRootCause || incident.description || 'System component failure or operational anomaly occurred.',
      },
      {
        why: 'Why was the failure or degradation not caught immediately?',
        answer: 'Early warning monitoring thresholds were not met or automated alerts were delayed.',
      },
      {
        why: 'Why were the monitoring safeguards or alerts insufficient?',
        answer: 'System configuration and preventive checks did not cover this specific failure condition.',
      },
      {
        why: 'Why were preventive checks or procedures not in place?',
        answer: 'Comprehensive operational risk reviews and automated health probes need further refinement.',
      },
    ],
  };
}
