import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

async function getAIConfig() {
  try {
    const settings = await prisma.systemSetting.findMany({
      where: { key: { in: ['GEMINI_API_KEY', 'AI_MODEL'] } },
    });
    const keySetting = settings.find((s) => s.key === 'GEMINI_API_KEY');
    const modelSetting = settings.find((s) => s.key === 'AI_MODEL');
    return {
      apiKey: keySetting?.value || process.env.GEMINI_API_KEY || null,
      model: modelSetting?.value || 'gemini-1.5-flash',
    };
  } catch {
    return { apiKey: process.env.GEMINI_API_KEY || null, model: 'gemini-1.5-flash' };
  }
}

function escapeHtml(str: any): string {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatDate(d: Date | string | null | undefined): string {
  if (!d) return 'N/A';
  const date = new Date(d);
  if (isNaN(date.getTime())) return 'N/A';
  return date.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
}

export async function GET(request: Request, { params }: { params: { id: string } }) {
  const { searchParams } = new URL(request.url);
  const rcaDataParam = searchParams.get('rcaData');
  let passedRca: any = null;
  if (rcaDataParam) {
    try {
      const parsed = JSON.parse(rcaDataParam);
      passedRca = parsed.autoGeneratedRca || parsed.rca || parsed;
    } catch (err) {
      console.warn('[RCA Export] Failed to parse rcaData query param:', err);
    }
  }
  return handleExport(params.id, passedRca);
}

export async function POST(request: Request, { params }: { params: { id: string } }) {
  let passedRca: any = null;
  try {
    const body = await request.json();
    passedRca = body?.rcaData?.autoGeneratedRca || body?.rcaData || body;
  } catch {
    // Body is optional
  }
  return handleExport(params.id, passedRca);
}

async function handleExport(id: string, passedRca: any) {
  try {
    const incident = await prisma.incident.findFirst({
      where: { OR: [{ id }, { number: id }] },
      include: {
        updates: { orderBy: { updateNumber: 'asc' } },
        sites: { include: { site: true } },
      },
    });

    if (!incident) {
      return NextResponse.json({ success: false, error: 'Incident not found' }, { status: 404 });
    }

    // Build RCA fields combining passed data and incident fields
    const finalUpdate = incident.updates.find((u) => u.isFinal);
    const lastUpdate = incident.updates.length > 0 ? incident.updates[incident.updates.length - 1] : null;

    const summary =
      passedRca?.summary ||
      incident.aiExecutiveSummary ||
      `Incident ${incident.number} ("${incident.shortDescription}") was logged as a ${incident.priority} priority outage handled by ${incident.assignmentGroup}. ${
        incident.totalOutageDuration ? `Total service disruption duration was recorded at ${incident.totalOutageDuration}.` : 'The incident has been mitigated and resolved.'
      }`;

    const rootCause =
      passedRca?.rootCause ||
      incident.aiRootCause ||
      incident.issueSummary ||
      'Root cause analysis completed based on technical triage and timeline updates.';

    const impactAnalysis =
      passedRca?.impactAnalysis ||
      incident.aiBusinessImpact ||
      `The incident caused an operational disruption${
        incident.sites.length > 0 ? ` impacting ${incident.sites.length} site(s): ${incident.sites.map((s) => s.site.name).join(', ')}` : ''
      }. Priority level ${incident.priority} required immediate coordination and triage.`;

    let resolutionSteps: string[] = [];
    if (Array.isArray(passedRca?.resolutionSteps) && passedRca.resolutionSteps.length > 0) {
      resolutionSteps = passedRca.resolutionSteps;
    } else if (incident.aiDoneSoFar) {
      resolutionSteps = incident.aiDoneSoFar
        .split('\n')
        .map((s: string) => s.replace(/^[-*•\d.]+\s*/, '').trim())
        .filter(Boolean);
    } else if (finalUpdate) {
      resolutionSteps = [finalUpdate.comment];
    } else if (lastUpdate) {
      resolutionSteps = [lastUpdate.comment];
    } else {
      resolutionSteps = ['Investigated initial alert and isolated affected component.', 'Applied corrective remediation patch/configuration.', 'Validated service recovery and restored normal operations.'];
    }

    let preventiveMeasures: string[] = [];
    if (Array.isArray(passedRca?.preventiveMeasures) && passedRca.preventiveMeasures.length > 0) {
      preventiveMeasures = passedRca.preventiveMeasures;
    } else {
      preventiveMeasures = [
        'Conduct a comprehensive post-incident review (PIR) with key engineering and operations stakeholders.',
        'Review and harden health check probes and early-warning alerting thresholds.',
        'Update standard operating procedures (SOPs), runbooks, and failover validation tests.',
        'Evaluate system redundancy to minimize single points of failure.',
      ];
    }

    let lessonsLearned: string[] = [];
    if (Array.isArray(passedRca?.lessonsLearned) && passedRca.lessonsLearned.length > 0) {
      lessonsLearned = passedRca.lessonsLearned;
    } else {
      lessonsLearned = [
        'Ensure fast escalation pathways are maintained across partner leads and support groups.',
        'Maintain detailed chronological logs during bridge calls for faster post-incident reconstruction.',
        'Verify automated backup routes and secondary failover mechanisms on regular schedules.',
      ];
    }

    // 5 Why Analysis generation
    const fiveWhys = (passedRca?.fiveWhyAnalysis || passedRca?.fiveWhys || [
      {
        why: `Why did the service disruption occur for ${incident.cmdbCi || incident.businessService || incident.shortDescription}?`,
        answer: incident.shortDescription || 'The system experienced an unexpected loss of service availability and operational degradation.',
      },
      {
        why: 'Why was the primary service unable to process requests normally?',
        answer: incident.aiTechnicalSummary || incident.issueSummary || 'A critical subsystem component encountered a communication failure, configuration error, or resource bottleneck.',
      },
      {
        why: 'Why did this component fail or reach an error state?',
        answer: rootCause || 'The underlying trigger occurred during high load, synchronization failure, or external dependency interruption.',
      },
      {
        why: 'Why was the issue not automatically mitigated or isolated before user impact?',
        answer: incident.updates.length > 0
          ? `Mitigation required active manual triage by ${incident.assignmentGroup} to diagnose and deploy the appropriate corrective actions.`
          : 'Automated failover thresholds or self-healing safeguards were not triggered prior to user-visible symptoms.',
      },
      {
        why: 'Why did the root vulnerability or configuration gap exist?',
        answer: 'Ongoing gap in preventive validation, dependency monitoring, or architectural redundancy that is addressed in the preventive action items.',
      },
    ]).map((item: any) => ({
      why: item.why || item.question || 'Investigation question',
      answer: item.answer || item.because || (typeof item === 'string' ? item : 'Pending determination'),
    }));

    const impactedSitesList = incident.sites.map((s) => s.site.name).join(', ') || 'Global / All Sites';

    // Build the Word HTML Document
    const htmlContent = `<!DOCTYPE html>
<html xmlns:o='urn:schemas-microsoft-com:office:office'
      xmlns:w='urn:schemas-microsoft-com:office:word'
      xmlns='http://www.w3.org/TR/REC-html40'>
<head>
<meta charset="utf-8">
<title>Root Cause Analysis Report - ${escapeHtml(incident.number)}</title>
<!--[if gte mso 9]>
<xml>
  <w:WordDocument>
    <w:View>Print</w:View>
    <w:Zoom>100</w:Zoom>
    <w:DoNotOptimizeForBrowser/>
  </w:WordDocument>
</xml>
<![endif]-->
<style>
  @page Section1 {
    size: 8.5in 11.0in;
    margin: 1.0in 1.0in 1.0in 1.0in;
    mso-header-margin: 0.5in;
    mso-footer-margin: 0.5in;
    mso-paper-source: 0;
  }
  div.Section1 {
    page: Section1;
  }
  body {
    font-family: 'Calibri', 'Segoe UI', Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.45;
    color: #1e293b;
    background-color: #ffffff;
    margin: 0;
    padding: 0;
  }
  h1.doc-title {
    font-size: 22pt;
    font-weight: 700;
    color: #0f172a;
    margin: 0 0 4pt 0;
    padding-bottom: 6pt;
    border-bottom: 3pt solid #0284c7;
  }
  .doc-subtitle {
    font-size: 12pt;
    color: #64748b;
    margin-bottom: 16pt;
    font-weight: 500;
  }
  h2.section-header {
    font-size: 13pt;
    font-weight: 700;
    color: #0f172a;
    background-color: #f1f5f9;
    padding: 6pt 10pt;
    margin-top: 18pt;
    margin-bottom: 8pt;
    border-left: 4pt solid #0284c7;
  }
  h3.subsection-header {
    font-size: 11pt;
    font-weight: 700;
    color: #334155;
    margin-top: 10pt;
    margin-bottom: 4pt;
  }
  p {
    margin: 0 0 8pt 0;
  }
  table.data-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 12pt;
    font-size: 10pt;
  }
  table.data-table th {
    background-color: #0f172a;
    color: #ffffff;
    font-weight: 600;
    text-align: left;
    padding: 6pt 8pt;
    border: 1pt solid #cbd5e1;
  }
  table.data-table td {
    padding: 6pt 8pt;
    border: 1pt solid #cbd5e1;
    vertical-align: top;
  }
  table.data-table tr:nth-child(even) td {
    background-color: #f8fafc;
  }
  td.label-cell {
    font-weight: 600;
    background-color: #f1f5f9 !important;
    color: #334155;
    width: 22%;
  }
  td.value-cell {
    width: 28%;
    color: #0f172a;
  }
  .box {
    padding: 8pt 12pt;
    margin-bottom: 10pt;
    border-radius: 4pt;
    border: 1pt solid #e2e8f0;
  }
  .box-executive {
    background-color: #f0fdf4;
    border-left: 4pt solid #16a34a;
    border-color: #bbf7d0;
  }
  .box-root-cause {
    background-color: #fef2f2;
    border-left: 4pt solid #dc2626;
    border-color: #fca5a5;
  }
  .box-impact {
    background-color: #fffbeb;
    border-left: 4pt solid #d97706;
    border-color: #fde68a;
  }
  .box-resolution {
    background-color: #f0f9ff;
    border-left: 4pt solid #0284c7;
    border-color: #bae6fd;
  }
  .badge {
    display: inline-block;
    padding: 2pt 6pt;
    font-size: 9pt;
    font-weight: 700;
    border-radius: 3pt;
  }
  .badge-p1 { background-color: #fee2e2; color: #991b1b; }
  .badge-p2 { background-color: #ffedd5; color: #9a3412; }
  .badge-p3 { background-color: #fef9c3; color: #854d0e; }
  .badge-p4 { background-color: #dcfce7; color: #166534; }
  ol, ul {
    margin: 4pt 0 10pt 0;
    padding-left: 20pt;
  }
  li {
    margin-bottom: 4pt;
    color: #334155;
  }
  .footer {
    margin-top: 24pt;
    padding-top: 8pt;
    border-top: 1pt solid #cbd5e1;
    font-size: 8.5pt;
    color: #64748b;
    text-align: center;
  }
</style>
</head>
<body>
<div class="Section1">

  <!-- Document Header -->
  <h1 class="doc-title">Root Cause Analysis Report</h1>
  <div class="doc-subtitle">Incident Reference: ${escapeHtml(incident.number)} &bull; ${escapeHtml(incident.shortDescription)}</div>

  <!-- Incident Details Section -->
  <h2 class="section-header">1. Incident Overview &amp; Details</h2>
  <table class="data-table">
    <tr>
      <td class="label-cell">Incident Number</td>
      <td class="value-cell"><strong>${escapeHtml(incident.number)}</strong></td>
      <td class="label-cell">Priority</td>
      <td class="value-cell"><span class="badge badge-${incident.priority.toLowerCase()}">${escapeHtml(incident.priority)}</span></td>
    </tr>
    <tr>
      <td class="label-cell">Current Status</td>
      <td class="value-cell"><strong>${escapeHtml(incident.status)}</strong></td>
      <td class="label-cell">Total Outage Duration</td>
      <td class="value-cell">${escapeHtml(incident.totalOutageDuration || 'N/A')}</td>
    </tr>
    <tr>
      <td class="label-cell">Opened At</td>
      <td class="value-cell">${formatDate(incident.openedAt)}</td>
      <td class="label-cell">Resolved At</td>
      <td class="value-cell">${formatDate(incident.resolvedAt || incident.closedAt)}</td>
    </tr>
    <tr>
      <td class="label-cell">Assignment Group</td>
      <td class="value-cell">${escapeHtml(incident.assignmentGroup)}</td>
      <td class="label-cell">Assigned To</td>
      <td class="value-cell">${escapeHtml(incident.assignedTo || 'Unassigned')}</td>
    </tr>
    <tr>
      <td class="label-cell">CMDB Configuration Item</td>
      <td class="value-cell">${escapeHtml(incident.cmdbCi || 'N/A')}</td>
      <td class="label-cell">Business Service</td>
      <td class="value-cell">${escapeHtml(incident.businessService || 'N/A')}</td>
    </tr>
    <tr>
      <td class="label-cell">Category (CTI)</td>
      <td class="value-cell">${escapeHtml(incident.cti || 'N/A')}</td>
      <td class="label-cell">Impacted Sites</td>
      <td class="value-cell">${escapeHtml(impactedSitesList)}</td>
    </tr>
    ${
      incident.partnerLead || incident.cdItCoordinator || incident.teamsInvolved || incident.relatedIncidents
        ? `
    <tr>
      <td class="label-cell">Partner Lead</td>
      <td class="value-cell">${escapeHtml(incident.partnerLead || 'N/A')}</td>
      <td class="label-cell">C&amp;D IT Coordinator</td>
      <td class="value-cell">${escapeHtml(incident.cdItCoordinator || 'N/A')}</td>
    </tr>
    <tr>
      <td class="label-cell">Teams Involved</td>
      <td class="value-cell">${escapeHtml(incident.teamsInvolved || 'N/A')}</td>
      <td class="label-cell">Related Incidents</td>
      <td class="value-cell">${escapeHtml(incident.relatedIncidents || 'None')}</td>
    </tr>`
        : ''
    }
  </table>

  <!-- Executive Summary Section -->
  <h2 class="section-header">2. Executive Summary</h2>
  <div class="box box-executive">
    <p style="margin:0; font-size:10.5pt; color:#14532d; font-weight:500;">
      ${escapeHtml(summary)}
    </p>
  </div>

  <!-- Root Cause Section -->
  <h2 class="section-header">3. Root Cause Statement</h2>
  <div class="box box-root-cause">
    <p style="margin:0; font-size:10.5pt; color:#7f1d1d; font-weight:500;">
      <strong>Primary Root Cause:</strong> ${escapeHtml(rootCause)}
    </p>
  </div>

  <!-- 5 Why Analysis Section -->
  <h2 class="section-header">4. 5 Why Analysis</h2>
  <p style="font-size:10pt; color:#64748b; margin-bottom:6pt;">Iterative interrogative technique used to explore the cause-and-effect relationships underlying the failure:</p>
  <table class="data-table">
    <thead>
      <tr>
        <th style="width:10%;">#</th>
        <th style="width:40%;">Investigation Stage ("Why" Question)</th>
        <th style="width:50%;">Findings &amp; Root Cause Deductions</th>
      </tr>
    </thead>
    <tbody>
      ${fiveWhys
        .map(
          (item: any, idx: number) => `
      <tr>
        <td style="text-align:center; font-weight:bold;">Why ${idx + 1}</td>
        <td><strong>${escapeHtml(item.why || item.question || `Why step ${idx + 1}?`)}</strong></td>
        <td>${escapeHtml(item.answer || item.because || item)}</td>
      </tr>`
        )
        .join('')}
    </tbody>
  </table>

  <!-- Impact Analysis Section -->
  <h2 class="section-header">5. Business &amp; Technical Impact Analysis</h2>
  <div class="box box-impact">
    <h3 class="subsection-header" style="color:#78350f; margin-top:0;">Business &amp; Operational Impact:</h3>
    <p style="font-size:10pt; color:#92400e; margin-bottom:8pt;">
      ${escapeHtml(impactAnalysis)}
    </p>
    ${
      incident.aiTechnicalSummary
        ? `
    <h3 class="subsection-header" style="color:#78350f;">Technical Scope:</h3>
    <p style="font-size:10pt; color:#92400e; margin-bottom:0;">
      ${escapeHtml(incident.aiTechnicalSummary)}
    </p>`
        : ''
    }
  </div>

  <!-- Timeline of Events Section -->
  <h2 class="section-header">6. Timeline of Events</h2>
  <table class="data-table">
    <thead>
      <tr>
        <th style="width:8%;">Update #</th>
        <th style="width:22%;">Timestamp</th>
        <th style="width:20%;">Author / Submitter</th>
        <th style="width:50%;">Details &amp; Action Taken</th>
      </tr>
    </thead>
    <tbody>
      ${
        incident.updates.length > 0
          ? incident.updates
              .map(
                (u) => `
      <tr>
        <td style="text-align:center; font-weight:bold;">#${u.updateNumber}</td>
        <td>${formatDate(u.createdAt)}</td>
        <td>${escapeHtml(u.authorName)} ${u.isFinal ? '<span class="badge" style="background-color:#dcfce7; color:#166534; font-size:8pt;">Final</span>' : ''}</td>
        <td>${escapeHtml(u.comment)}</td>
      </tr>`
              )
              .join('')
          : `
      <tr>
        <td colspan="4" style="text-align:center; color:#94a3b8;">No update log entries recorded for this incident.</td>
      </tr>`
      }
    </tbody>
  </table>

  <!-- Resolution Steps Section -->
  <h2 class="section-header">7. Resolution Steps Taken</h2>
  <div class="box box-resolution">
    <ol style="margin-bottom:0;">
      ${resolutionSteps.map((step) => `<li>${escapeHtml(step)}</li>`).join('')}
    </ol>
  </div>

  <!-- Preventive Measures Section -->
  <h2 class="section-header">8. Preventive Measures &amp; Action Items</h2>
  <ul>
    ${preventiveMeasures.map((measure) => `<li>${escapeHtml(measure)}</li>`).join('')}
  </ul>

  <!-- Lessons Learned Section -->
  <h2 class="section-header">9. Lessons Learned</h2>
  <ul>
    ${lessonsLearned.map((lesson) => `<li>${escapeHtml(lesson)}</li>`).join('')}
  </ul>

  <!-- Resolution Summary Section -->
  <h2 class="section-header">10. Resolution Summary</h2>
  <table class="data-table">
    <tr>
      <td class="label-cell">Resolution Status</td>
      <td class="value-cell">${escapeHtml(incident.status)}</td>
      <td class="label-cell">Resolution Timestamp</td>
      <td class="value-cell">${formatDate(incident.resolvedAt || incident.closedAt)}</td>
    </tr>
    <tr>
      <td class="label-cell">Total Outage Duration</td>
      <td class="value-cell">${escapeHtml(incident.totalOutageDuration || 'N/A')}</td>
      <td class="label-cell">Estimated Time to Resolve</td>
      <td class="value-cell">${incident.ettrMinutes} minutes</td>
    </tr>
    ${
      incident.aiDoneSoFar
        ? `
    <tr>
      <td class="label-cell">What Was Completed</td>
      <td class="value-cell" colspan="3">${escapeHtml(incident.aiDoneSoFar)}</td>
    </tr>`
        : ''
    }
    ${
      incident.aiWhatIsAwaited
        ? `
    <tr>
      <td class="label-cell">Pending / Post-Closure Items</td>
      <td class="value-cell" colspan="3">${escapeHtml(incident.aiWhatIsAwaited)}</td>
    </tr>`
        : ''
    }
  </table>

  <!-- Document Footer -->
  <div class="footer">
    CIM Outage Centre &bull; Root Cause Analysis (RCA) Report &bull; Generated on ${new Date().toUTCString()}
  </div>

</div>
</body>
</html>`;

    // Create audit log for export action
    try {
      await prisma.auditLog.create({
        data: {
          userName: 'Incident Manager',
          userRole: 'INCIDENT_MANAGER',
          action: 'RCA_EXPORTED',
          details: `Exported RCA Report (.doc) for incident ${incident.number}`,
        },
      });
    } catch (auditErr) {
      console.warn('[RCA Export] Failed to record audit log:', auditErr);
    }

    // Set response headers for Word document download
    const filename = `RCA_Report_${incident.number || id}.doc`;

    return new Response(htmlContent, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (err: any) {
    console.error('[RCA Export API] Error:', err.message);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
